In [1]:
import numpy as np


In [2]:
a = np.arange(1,4)

In [3]:
a

array([1, 2, 3])

In [4]:
b = a


In [5]:
a is b

True

In [6]:
a == b

array([ True,  True,  True])

In [7]:
a.dot(b)

14

In [11]:
c = np.c_[a, b]

In [12]:
c

array([[1, 1],
       [2, 2],
       [3, 3]])

In [13]:
c.dot(a)

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [14]:
np.dot(a, c)

array([14, 14])

In [15]:
np.dot(c, a)

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [16]:
np.dot(a, a)

14

In [17]:
c @ c

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [18]:
c.shape

(3, 2)

In [19]:
np.dot(c, c)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [24]:
d = np.dot(c, c.T)
d

array([[ 2,  4,  6],
       [ 4,  8, 12],
       [ 6, 12, 18]])

In [22]:
d.dot(2)

array([[ 4,  8, 12],
       [ 8, 16, 24],
       [12, 24, 36]])