In [1]:
import numpy as np


In [14]:
m, n = 3,2



In [16]:
X = np.random.randint(0, 3, m * n).reshape(m,n)

In [17]:
X

array([[1, 2],
       [1, 2],
       [1, 0]])

In [19]:
X = X.T.dot(X)

In [38]:
X

array([[3, 4],
       [4, 8]])

In [39]:
np.linalg.det(X)

7.999999999999998

In [33]:
X_inv = np.linalg.inv(X)
X_inv

array([[ 1.   , -0.5  ],
       [-0.5  ,  0.375]])

In [27]:
I = X.dot(X_inv)
I

array([[1., 0.],
       [0., 1.]])

In [28]:
# Consider m < n 

In [45]:
m,n = 2, 3
X1 = np.random.randint(0, 3, m * n).reshape(m, n)
X1

array([[2, 0, 2],
       [0, 1, 1]])

In [46]:
X1 = X1.T.dot(X1)
X1


array([[4, 0, 4],
       [0, 1, 1],
       [4, 1, 5]])

In [47]:
np.linalg.det(X1)

0.0

In [48]:
X1_inv = np.linalg.inv(X1)
X1_inv

LinAlgError: Singular matrix

In [49]:
I1 = X1.dot(X1_inv)
I1

array([[-3.43131400e+15,  1.71565700e+15,  2.57348550e+15],
       [ 4.28914250e+15, -2.14457125e+15, -3.21685688e+15],
       [ 8.57828500e+14, -4.28914250e+14, -6.43371375e+14]])

In [50]:
R1 =  X1.dot(X1_inv)
R1

array([[-3.43131400e+15,  1.71565700e+15,  2.57348550e+15],
       [ 4.28914250e+15, -2.14457125e+15, -3.21685688e+15],
       [ 8.57828500e+14, -4.28914250e+14, -6.43371375e+14]])